controllers:
    resource: ../src/Controller/
    type: annotation

app_bundle_controller:
    resource: ../src/Controller/Admin
    type: annotation
    prefix: /admin4552255
    
kernel:
    resource: ../src/Kernel.php
    type: annotation
