controllers:
    resource: ../src/Controller/
    type: attribute

app_bundle_controller:
    resource: ../src/Controller/Admin
    type: attribute
    prefix: /admin4552255
    
kernel:
    resource: ../src/Kernel.php
    type: attribute
